### ISSUE TITLE
docky migrate is broken

### ISSUE THREAD

**Issue by rvalyi** [akretion/docky#120]
1st error:
```
Traceback (most recent call last):
  File "/usr/local/bin/docky", line 11, in <module>
    load_entry_point('docky==5.0.2', 'console_scripts', 'docky')()
  File "/usr/local/lib/python3.6/dist-packages/docky/main.py", line 7, in main
    Docky.run()
  File "/usr/local/lib/python3.6/dist-packages/plumbum/cli/application.py", line 577, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/usr/local/lib/python3.6/dist-packages/plumbum/cli/application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "/usr/local/lib/python3.6/dist-packages/docky/cmd/base.py", line 77, in main
    self._main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docky/cmd/migrate.py", line 50, in _main
    if self.main_service != 'odoo':
AttributeError: 'DockyMigrate' object has no attribute 'main_service'
```

after I removed the check, I got an import error, showing the migrate command was not tested on recent Docky versions:

```
Traceback (most recent call last):
  File "/usr/local/bin/docky", line 11, in <module>
    load_entry_point('docky==5.0.2', 'console_scripts', 'docky')()
  File "/usr/local/lib/python3.6/dist-packages/docky/main.py", line 7, in main
    Docky.run()
  File "/usr/local/lib/python3.6/dist-packages/plumbum/cli/application.py", line 577, in run
    inst, retcode = subapp.run(argv, exit=False)
  File "/usr/local/lib/python3.6/dist-packages/plumbum/cli/application.py", line 572, in run
    retcode = inst.main(*tailargs)
  File "/usr/local/lib/python3.6/dist-packages/docky/cmd/base.py", line 77, in main
    self._main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/docky/cmd/migrate.py", line 56, in _main
    start = datetime.now()
NameError: name 'datetime' is not defined
```

Stopped here for now sorry.

**Comment by rvalyi** [comment]
migrate cmd has been removed so closing
