### ISSUE TITLE
master install copier error

### ISSUE THREAD

**Issue by rvalyi** [akretion/docky#148]
@hparfr may be related to your latest changes?

```
/usr/bin/pip3 install git+https://github.com/akretion/docky
Collecting git+https://github.com/akretion/docky
  Cloning https://github.com/akretion/docky to /tmp/pip-req-build-xvo6ww_f
Collecting copier@ git+https://github.com/hparfr/copier@vcs_branch22-04#egg=copier from git+https://github.com/hparfr/copier@vcs_branch22-04#egg=copier (from docky==7.0.7)
  Cloning https://github.com/hparfr/copier (to revision vcs_branch22-04) to /tmp/pip-install-aocvb3gl/copier
Branch 'vcs_branch22-04' set up to track remote branch 'vcs_branch22-04' from 'origin'.
Switched to a new branch 'vcs_branch22-04'
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-aocvb3gl/copier/setup.py'
```

tried with both pip 18 and 22.0.4

**Comment by rvalyi** [comment]
@hparfr in fact `sudo python3 -m pip install git+https://github.com/akretion/docky` just works as expected. What doesn't work is `/usr/bin/pip3 install git+https://github.com/akretion/docky` but it seems it's what our "docky" Ansible does sadly. That's the second server where I got the same error. So closing as it seems more of a problem in our Ansible recipe.

**Comment by rvalyi** [comment]
so in fact I had the issue even with `sudo python3 -m pip install git+https://github.com/akretion/docky`
and I had to do this before to fix it: `sudo python3 -m pip install --upgrade pip setuptools`
