### ISSUE TITLE
ak run should trigger ak build if required

### ISSUE THREAD

**Issue by rvalyi** [akretion/docky#48]
instead of just failing hard

**Comment by rvalyi** [comment]
currently it will fail hard with that log:
```
odoo@8b7fbd0cf4e3:/workspace$ ak run
Traceback (most recent call last):
  File "/usr/local/bin/ak", line 9, in <module>
    load_entry_point('ak==1.1.1', 'console_scripts', 'ak')()
  File "/usr/local/lib/python2.7/dist-packages/ak/main.py", line 313, in main
    Ak.run()
  File "/usr/local/lib/python2.7/dist-packages/plumbum/cli/application.py", line 485, in run
    inst, retcode = subapp.run(argv, exit = False)
  File "/usr/local/lib/python2.7/dist-packages/plumbum/cli/application.py", line 480, in run
    retcode = inst.main(*tailargs)
  File "/usr/local/lib/python2.7/dist-packages/ak/main.py", line 87, in main
    return self._exec('bin/start_openerp', self.argv)
  File "/usr/local/lib/python2.7/dist-packages/ak/main.py", line 71, in _exec
    return self.parent._exec(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ak/main.py", line 46, in _exec
    os.execvpe(cmd, [cmd] + args, local.env)
  File "/usr/lib/python2.7/os.py", line 355, in execvpe
    _execvpe(file, args, env)
  File "/usr/lib/python2.7/os.py", line 370, in _execvpe
    func(file, *argrest)
OSError: [Errno 2] No such file or directory
```

so the work around is to run ak buid and then ak run, but this is not user friendly.

**Comment by bealdav** [comment]
pareil pour moi

**Comment by bealdav** [comment]
newcomers could be `bouhouhou` ! don't you think @sebastienbeau
